# Site settings
title: Ziao Liu
email: ziao_liu@outlook.com
description: > # this means to ignore newlines until "baseurl:"
  PhD Student at ZJU
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.ziaoliu.com" # the base hostname & protocol for your site
production_url: "https://www.ziaoliu.com"
github_username: ziao-liu
permalink: /blog/:year/:month/:title.html


sass:
  style: compressed

collections:
  publications:
    output: false

jekyll-mentions:
  base_url: https://twitter.com

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-mentions
